server:
  port: 9090
  context-path: /
  tomcat:
    uri-encoding: UTF-8
  main:
    banner-mode: "off"


attendance:
  cron: 1 0 0 0 1 ?
  shift:
    defaultId: 1
    allowAdvanceHours: -5
    allowDelayHours: 5
    delayHoursOnStartWork: 3

